#!/usr/bin/env python3
"""Render docs/delta/methods.md from delta.json.

Usage: python3 delta_tables.py [dir-with-delta.json] [output-file]
Defaults: this directory, and ../methods.md next to it. Standard library only.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else HERE.parent / "methods.md"
CAT = json.loads((SRC / "delta.json").read_text())
ENTRIES = CAT["entries"]
TARGET = {350000: "350k", 5000000: "5M", 1400000: "1.4M"}


def targets(ts):
    return ", ".join(TARGET[t] for t in ts) or "none"


def delta(cfg):
    parts = []
    for k, v in cfg.items():
        vv = v if isinstance(v, str) else json.dumps(v, separators=(",", ":"))
        parts.append(f"`{k}={vv}`")
    return "; ".join(parts) or "none"


def num(v):
    return "n/a" if v is None else f"{v:,}"


def floor(e):
    f = e["floor"]
    if f["floor0"] is None:
        return "needs the body's own shapes"
    s = f"{num(f['floor0'])} / {num(f['floor1_alive'])}"
    h = f["headroom_by_target"].get("350000")
    if isinstance(h, float):
        s += f"; h {h:.3f}"
    on = f.get("on_d24h2")
    if on:
        hh = on["headroom_350000"]
        s += "; on d24h2: h " + (f"{hh:.3f}" if isinstance(hh, float) else "n/a")
    return s


def cell(text):
    return (text or "none").replace("|", "/")


lines = [
    "# Delta method table",
    "",
    "Generated by `catalogue/delta_tables.py` from `catalogue/delta.json`; edit `catalogue/delta_spec.py`,",
    "not this file. Nothing in this table has been trained. The columns are defined in [rules.md](rules.md):",
    "the targets are EBOPs budgets (screen, then confirm), H is the screen horizon in epochs, and the last",
    "numeric column gives the 0-bit and 1-bit-alive EBOPs floors of the entry's own architecture,",
    "computed from layer shapes, with h the headroom fraction at 350k (clipped at 1). \"On d24h2\" gives",
    "h after the change is moved onto the 350k base.",
    "",
    f"{len(ENTRIES)} entries: {sum(e['tier'] in ('single', 'baseline') for e in ENTRIES)} singles and baselines, "
    f"{sum(e['tier'] in ('package', 'factorial-cell') for e in ENTRIES)} combinations.",
    "",
    "## Singles and baselines (M001-M050)",
    "",
    "| ID | name | family | cards | mechanisms | change from the base | code tier / changes | tried before | targets (screen → confirm) | H | pairing | prediction | mechanism diagnostic | floors (computed from layer shapes) | note |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
]
for e in ENTRIES:
    if e["tier"] not in ("single", "baseline"):
        continue
    cc = ", ".join(f"`{p}`" for p in e["code_changes"]) or "none"
    lines.append(
        f"| {e['id']} | {e['name']} | {e['family']} | {', '.join(e['cards'])} | {', '.join(e['mechanisms'])} | "
        f"{delta(e['config_delta'])} | {e['code_tier']}: {cc} | {cell(e['tried'])} | "
        f"{targets(e['targets'])} → {targets(e['targets_confirm'])} | {e['horizon_screen_epochs']} | {cell(e['pairing'])} | "
        f"{cell(e['prediction'])} | {cell(e['mechanism_diagnostic'])} | {floor(e)} | {cell(e['note'])} |")
lines += [
    "",
    "## Combinations (M051-M103)",
    "",
    "| ID | package | family | components | decomposition ladder | extra change, note | code tier | targets (screen → confirm) | H | pairing | prediction | diagnostic | floors (computed from layer shapes) |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
]
for e in ENTRIES:
    if e["tier"] not in ("package", "factorial-cell"):
        continue
    comp = " + ".join(e["combo_of"]) or "none"
    extra = "; ".join(x for x in [delta(e["extra_delta"]) if e["extra_delta"] else "", e["note"]] if x) or "none"
    lines.append(
        f"| {e['id']} | {e['name']} | {e['family']} | {comp} | {', '.join(e['ladder'])} | {cell(extra)} | {e['code_tier']} | "
        f"{targets(e['targets'])} → {targets(e['targets_confirm'])} | {e['horizon_screen_epochs']} | {cell(e['pairing'])} | "
        f"{cell(e['prediction'])} | {cell(e['mechanism_diagnostic'])} | {floor(e)} |")
lines += [
    "",
    "## Static floors by architecture",
    "",
    "Computed from layer shapes by `delta_spec.py` (formula in [rules.md](rules.md#static-floors)). \"Near-floor\"",
    "means h < 0.10.",
    "",
    "| architecture (entries) | 0-bit floor | 1-bit-alive floor | h at 350k | class at 350k |",
    "| --- | ---: | ---: | ---: | --- |",
]
for r in CAT["architecture_floors"]:
    h = r["headroom_350000"]
    hs = f"{h:.3f}" if isinstance(h, float) else "–"
    cls = "`STATIC_INFEASIBLE`" if r["class_350000"] == "STATIC_INFEASIBLE" else r["class_350000"]
    lines.append(f"| {r['architecture']} | {num(r['floor0'])} | {num(r['floor1_alive'])} | {hs} | {cls} |")
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(lines)} lines)")
